# Create user
mutation CreateUser($name: String!, $email: String!, $role: String!, $phoneNumber: String!, $avatarUrl: String, $address: String) @auth(level: PUBLIC, insecureReason: "Enable user signup") {
  user_insert(data: {
    name: $name,
    email: $email,
    role: $role,
    phoneNumber: $phoneNumber,
    avatarUrl: $avatarUrl,
    address: $address,
    rating: 5.0
  })
}

# Create booking
mutation CreateBooking($status: String!, $bookingDate: Timestamp!, $totalAmount: Float!, $customerId: UUID!, $partnerId: UUID, $serviceCategoryId: UUID!) @auth(level: PUBLIC, insecureReason: "Create booking request") {
  booking_insert(data: {
    status: $status,
    bookingDate: $bookingDate,
    totalAmount: $totalAmount,
    customerId: $customerId,
    partnerId: $partnerId,
    serviceCategoryId: $serviceCategoryId
  })
}

# Create Review
mutation AddReview($rating: Int!, $comment: String!, $createdAt: Timestamp!, $partnerId: UUID!, $customerId: UUID @retired) @auth(level: USER) {
  review_insert(data: {
    rating: $rating,
    comment: $comment,
    createdAt: $createdAt,
    partnerId: $partnerId,
    customerId_expr: "auth.uid"
  })
}
