extend type Booking {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Booking", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`customer`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  customerId: UUID! @fdc_generated(from: "Booking.customer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`partner`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  partnerId: UUID @fdc_generated(from: "Booking.partner", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`serviceCategory`. It must match the value of `ServiceCategory`.`id`. See `@ref` for how to customize it.
  """
  serviceCategoryId: UUID! @fdc_generated(from: "Booking.serviceCategory", purpose: IMPLICIT_REF_FIELD)
}
extend type PartnerAvailability {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PartnerAvailability", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PartnerAvailability`.`partner`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  partnerId: UUID! @fdc_generated(from: "PartnerAvailability.partner", purpose: IMPLICIT_REF_FIELD)
}
extend type Review {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Review", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`customer`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  customerId: UUID! @fdc_generated(from: "Review.customer", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`partner`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  partnerId: UUID! @fdc_generated(from: "Review.partner", purpose: IMPLICIT_REF_FIELD)
}
extend type ServiceCategory {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ServiceCategory", purpose: IMPLICIT_KEY_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
