type User @table {
  name: String!
  email: String!
  role: String! # CUSTOMER | PARTNER
  phoneNumber: String!
  avatarUrl: String
  address: String
  rating: Float
}

type ServiceCategory @table {
  name: String!
  basePrice: Float!
  iconUrl: String
  description: String
}

type Booking @table {
  status: String! # PENDING | IN_PROGRESS | COMPLETED | CANCELLED
  bookingDate: Timestamp!
  totalAmount: Float!
  partnerNotes: String
  customerReview: String
  customer: User!
  partner: User
  serviceCategory: ServiceCategory!
}

type PartnerAvailability @table {
  startTime: Timestamp!
  endTime: Timestamp!
  isBooked: Boolean!
  partner: User!
}

type Review @table {
  rating: Int!
  comment: String!
  createdAt: Timestamp!
  partner: User!
  customer: User!
}
